### ISSUE TITLE
Update the API which has been deprecated.

### ISSUE THREAD

**Issue by Priyanshu-Batham** [Priyanshu-Batham/currencyConvertor#1]
The API previously used in the backend has been depricated and the maintainer has a full docs for the new API which can be read from here
[NEW API](https://github.com/fawazahmed0/exchange-api/blob/main/MIGRATION.md)

Replace the old API with the new one.

**Comment by akash70629** [comment]
@Priyanshu-Batham Please assign me this issue.

**Comment by Priyanshu-Batham** [comment]
@akash70629 
Here you go.
